export interface Country {
    id: number;
    code: string;
    flag: string;
    name: string;
}

export const countries: Country[] = [
    { id: 1, code: "+93", flag: "🇦🇫", name: "Afghanistan" },
    { id: 2, code: "+355", flag: "🇦🇱", name: "Albania" },
    { id: 3, code: "+213", flag: "🇩🇿", name: "Algeria" },
    { id: 4, code: "+1684", flag: "🇦🇸", name: "American Samoa" },
    { id: 5, code: "+376", flag: "🇦🇩", name: "Andorra" },
    { id: 6, code: "+244", flag: "🇦🇴", name: "Angola" },
    { id: 7, code: "+1264", flag: "🇦🇮", name: "Anguilla" },
    { id: 8, code: "+1268", flag: "🇦🇬", name: "Antigua and Barbuda" },
    { id: 9, code: "+54", flag: "🇦🇷", name: "Argentina" },
    { id: 10, code: "+374", flag: "🇦🇲", name: "Armenia" },
    { id: 11, code: "+297", flag: "🇦🇼", name: "Aruba" },
    { id: 12, code: "+61", flag: "🇦🇺", name: "Australia" },
    { id: 13, code: "+43", flag: "🇦🇹", name: "Austria" },
    { id: 14, code: "+994", flag: "🇦🇿", name: "Azerbaijan" },
    { id: 15, code: "+1242", flag: "🇧🇸", name: "Bahamas" },
    { id: 16, code: "+973", flag: "🇧🇭", name: "Bahrain" },
    { id: 17, code: "+880", flag: "🇧🇩", name: "Bangladesh" },
    { id: 18, code: "+1246", flag: "🇧🇧", name: "Barbados" },
    { id: 19, code: "+375", flag: "🇧🇾", name: "Belarus" },
    { id: 20, code: "+32", flag: "🇧🇪", name: "Belgium" },
    { id: 21, code: "+501", flag: "🇧🇿", name: "Belize" },
    { id: 22, code: "+229", flag: "🇧🇯", name: "Benin" },
    { id: 23, code: "+1441", flag: "🇧🇲", name: "Bermuda" },
    { id: 24, code: "+975", flag: "🇧🇹", name: "Bhutan" },
    { id: 25, code: "+591", flag: "🇧🇴", name: "Bolivia" },
    { id: 26, code: "+387", flag: "🇧🇦", name: "Bosnia and Herzegovina" },
    { id: 27, code: "+267", flag: "🇧🇼", name: "Botswana" },
    { id: 28, code: "+55", flag: "🇧🇷", name: "Brazil" },
    { id: 29, code: "+246", flag: "🇮🇴", name: "British Indian Ocean Territory" },
    { id: 30, code: "+1284", flag: "🇻🇬", name: "British Virgin Islands" },
    { id: 31, code: "+673", flag: "🇧🇳", name: "Brunei" },
    { id: 32, code: "+359", flag: "🇧🇬", name: "Bulgaria" },
    { id: 33, code: "+226", flag: "🇧🇫", name: "Burkina Faso" },
    { id: 34, code: "+257", flag: "🇧🇮", name: "Burundi" },
    { id: 35, code: "+237", flag: "🇨🇲", name: "Cameroon" },
    { id: 36, code: "+1", flag: "🇨🇦", name: "Canada" },
    { id: 37, code: "+238", flag: "🇨🇻", name: "Cape Verde" },
    { id: 38, code: "+269", flag: "🇰🇲", name: "Comoros" },
    { id: 39, code: "+243", flag: "🇨🇩", name: "Congo (DRC)" },
    { id: 40, code: "+242", flag: "🇨🇬", name: "Congo (Republic)" },
    { id: 41, code: "+682", flag: "🇨🇰", name: "Cook Islands" },
    { id: 42, code: "+506", flag: "🇨🇷", name: "Costa Rica" },
    { id: 43, code: "+225", flag: "🇨🇮", name: "Côte d’Ivoire" },
    { id: 44, code: "+351", flag: "🇵🇹", name: "Portugal" },
    { id: 45, code: "+1", flag: "🇺🇸", name: "USA" },
    { id: 46, code: "+213", flag: "🇩🇿", name: "Algeria" },
];